from kt_api_master import KT_API_MASTER
from cv_api_master import CV_API_MASTER
from nlp_api_master import NLP_API_MASTER

API_MASTER = {
    "path": "api/",
    "title": "Keras 3 API documentation",
    "toc": True,
    "children": [
        {
            "path": "models/",
            "title": "Models API",
            "toc": True,
            "children": [
                {
                    "path": "model",
                    "title": "The Model class",
                    "generate": [
                        "keras.Model",
                        "keras.Model.summary",
                        "keras.Model.get_layer",
                    ],
                },
                {
                    "path": "sequential",
                    "title": "The Sequential class",
                    "generate": [
                        "keras.Sequential",
                        "keras.Sequential.add",
                        "keras.Sequential.pop",
                    ],
                },
                {
                    "path": "model_training_apis",
                    "title": "Model training APIs",
                    "generate": [
                        "keras.Model.compile",
                        "keras.Model.fit",
                        "keras.Model.evaluate",
                        "keras.Model.predict",
                        "keras.Model.train_on_batch",
                        "keras.Model.test_on_batch",
                        "keras.Model.predict_on_batch",
                    ],
                },
                {
                    "path": "model_saving_apis/",
                    "title": "Saving & serialization",
                    "toc": True,
                    "children": [
                        {
                            "path": "model_saving_and_loading",
                            "title": "Whole model saving & loading",
                            "generate": [
                                "keras.Model.save",
                                "keras.saving.save_model",
                                "keras.saving.load_model",
                            ],
                        },
                        {
                            "path": "weights_saving_and_loading",
                            "title": "Weights-only saving & loading",
                            "generate": [
                                "keras.Model.save_weights",
                                "keras.Model.load_weights",
                            ],
                        },
                        {
                            "path": "model_config_serialization",
                            "title": "Model config serialization",
                            "generate": [
                                "keras.Model.get_config",
                                "keras.Model.from_config",
                                "keras.models.clone_model",
                            ],
                        },
                        {
                            "path": "export",
                            "title": "Model export for inference",
                            "generate": [
                                "keras.export.ExportArchive",
                            ],
                        },
                        {
                            "path": "serialization_utils",
                            "title": "Serialization utilities",
                            "generate": [
                                "keras.saving.serialize_keras_object",
                                "keras.saving.deserialize_keras_object",
                                "keras.saving.custom_object_scope",
                                "keras.saving.get_custom_objects",
                                "keras.saving.register_keras_serializable",
                            ],
                        },
                    ],
                },
            ],
        },
        {
            "path": "layers/",
            "title": "Layers API",
            "toc": True,
            "children": [
                {
                    "path": "base_layer",
                    "title": "The base Layer class",
                    "generate": [
                        "keras.layers.Layer",
                        "keras.layers.Layer.weights",
                        "keras.layers.Layer.trainable_weights",
                        "keras.layers.Layer.non_trainable_weights",
                        "keras.layers.Layer.add_weight",
                        "keras.layers.Layer.trainable",
                        "keras.layers.Layer.get_weights",
                        "keras.layers.Layer.set_weights",
                        "keras.Model.get_config",
                        "keras.layers.Layer.add_loss",
                        "keras.layers.Layer.losses",
                    ],
                },
                {
                    "path": "activations",
                    "title": "Layer activations",
                    "generate": [
                        "keras.activations.relu",
                        "keras.activations.sigmoid",
                        "keras.activations.softmax",
                        "keras.activations.softplus",
                        "keras.activations.softsign",
                        "keras.activations.tanh",
                        "keras.activations.selu",
                        "keras.activations.elu",
                        "keras.activations.exponential",
                        "keras.activations.leaky_relu",
                        "keras.activations.relu6",
                        "keras.activations.silu",
                        "keras.activations.gelu",
                        "keras.activations.hard_sigmoid",
                        "keras.activations.linear",
                        "keras.activations.mish",
                        "keras.activations.log_softmax",
                    ],
                },
                {
                    "path": "initializers",
                    "title": "Layer weight initializers",
                    "generate": [
                        "keras.initializers.RandomNormal",
                        "keras.initializers.RandomUniform",
                        "keras.initializers.TruncatedNormal",
                        "keras.initializers.Zeros",
                        "keras.initializers.Ones",
                        "keras.initializers.GlorotNormal",
                        "keras.initializers.GlorotUniform",
                        "keras.initializers.HeNormal",
                        "keras.initializers.HeUniform",
                        "keras.initializers.Orthogonal",
                        "keras.initializers.Constant",
                        "keras.initializers.VarianceScaling",
                    ],
                },
                {
                    "path": "regularizers",
                    "title": "Layer weight regularizers",
                    "generate": [
                        "keras.regularizers.L1",
                        "keras.regularizers.L2",
                        "keras.regularizers.L1L2",
                        "keras.regularizers.OrthogonalRegularizer",
                    ],
                },
                {
                    "path": "constraints",
                    "title": "Layer weight constraints",
                    "generate": [
                        "keras.constraints.MaxNorm",
                        "keras.constraints.MinMaxNorm",
                        "keras.constraints.NonNeg",
                        "keras.constraints.UnitNorm",
                    ],
                },
                {
                    "path": "core_layers/",
                    "title": "Core layers",
                    "toc": True,
                    "children": [
                        {
                            "path": "input",
                            "title": "Input object",
                            "generate": ["keras.Input"],
                        },
                        {
                            "path": "dense",
                            "title": "Dense layer",
                            "generate": ["keras.layers.Dense"],
                        },
                        {
                            "path": "activation",
                            "title": "Activation layer",
                            "generate": ["keras.layers.Activation"],
                        },
                        {
                            "path": "embedding",
                            "title": "Embedding layer",
                            "generate": ["keras.layers.Embedding"],
                        },
                        {
                            "path": "masking",
                            "title": "Masking layer",
                            "generate": ["keras.layers.Masking"],
                        },
                        {
                            "path": "lambda",
                            "title": "Lambda layer",
                            "generate": ["keras.layers.Lambda"],
                        },
                    ],
                },
                {
                    "path": "convolution_layers/",
                    "title": "Convolution layers",
                    "toc": True,
                    "children": [
                        {
                            "path": "convolution1d",
                            "title": "Conv1D layer",
                            "generate": ["keras.layers.Conv1D"],
                        },
                        {
                            "path": "convolution2d",
                            "title": "Conv2D layer",
                            "generate": ["keras.layers.Conv2D"],
                        },
                        {
                            "path": "convolution3d",
                            "title": "Conv3D layer",
                            "generate": ["keras.layers.Conv3D"],
                        },
                        {
                            "path": "separable_convolution1d",
                            "title": "SeparableConv1D layer",
                            "generate": ["keras.layers.SeparableConv1D"],
                        },
                        {
                            "path": "separable_convolution2d",
                            "title": "SeparableConv2D layer",
                            "generate": ["keras.layers.SeparableConv2D"],
                        },
                        {
                            "path": "depthwise_convolution2d",
                            "title": "DepthwiseConv2D layer",
                            "generate": ["keras.layers.DepthwiseConv2D"],
                        },
                        {
                            "path": "convolution1d_transpose",
                            "title": "Conv1DTranspose layer",
                            "generate": ["keras.layers.Conv1DTranspose"],
                        },
                        {
                            "path": "convolution2d_transpose",
                            "title": "Conv2DTranspose layer",
                            "generate": ["keras.layers.Conv2DTranspose"],
                        },
                        {
                            "path": "convolution3d_transpose",
                            "title": "Conv3DTranspose layer",
                            "generate": ["keras.layers.Conv3DTranspose"],
                        },
                    ],
                },
                {
                    "path": "pooling_layers/",
                    "title": "Pooling layers",
                    "toc": True,
                    "children": [
                        {
                            "path": "max_pooling1d",
                            "title": "MaxPooling1D layer",
                            "generate": ["keras.layers.MaxPooling1D"],
                        },
                        {
                            "path": "max_pooling2d",
                            "title": "MaxPooling2D layer",
                            "generate": ["keras.layers.MaxPooling2D"],
                        },
                        {
                            "path": "max_pooling3d",
                            "title": "MaxPooling3D layer",
                            "generate": ["keras.layers.MaxPooling3D"],
                        },
                        {
                            "path": "average_pooling1d",
                            "title": "AveragePooling1D layer",
                            "generate": ["keras.layers.AveragePooling1D"],
                        },
                        {
                            "path": "average_pooling2d",
                            "title": "AveragePooling2D layer",
                            "generate": ["keras.layers.AveragePooling2D"],
                        },
                        {
                            "path": "average_pooling3d",
                            "title": "AveragePooling3D layer",
                            "generate": ["keras.layers.AveragePooling3D"],
                        },
                        {
                            "path": "global_max_pooling1d",
                            "title": "GlobalMaxPooling1D layer",
                            "generate": ["keras.layers.GlobalMaxPooling1D"],
                        },
                        {
                            "path": "global_max_pooling2d",
                            "title": "GlobalMaxPooling2D layer",
                            "generate": ["keras.layers.GlobalMaxPooling2D"],
                        },
                        {
                            "path": "global_max_pooling3d",
                            "title": "GlobalMaxPooling3D layer",
                            "generate": ["keras.layers.GlobalMaxPooling3D"],
                        },
                        {
                            "path": "global_average_pooling1d",
                            "title": "GlobalAveragePooling1D layer",
                            "generate": ["keras.layers.GlobalAveragePooling1D"],
                        },
                        {
                            "path": "global_average_pooling2d",
                            "title": "GlobalAveragePooling2D layer",
                            "generate": ["keras.layers.GlobalAveragePooling2D"],
                        },
                        {
                            "path": "global_average_pooling3d",
                            "title": "GlobalAveragePooling3D layer",
                            "generate": ["keras.layers.GlobalAveragePooling3D"],
                        },
                    ],
                },
                {
                    "path": "recurrent_layers/",
                    "title": "Recurrent layers",
                    "toc": True,
                    "children": [
                        {
                            "path": "lstm",
                            "title": "LSTM layer",
                            "generate": ["keras.layers.LSTM"],
                        },
                        {
                            "path": "gru",
                            "title": "GRU layer",
                            "generate": ["keras.layers.GRU"],
                        },
                        {
                            "path": "simple_rnn",
                            "title": "SimpleRNN layer",
                            "generate": ["keras.layers.SimpleRNN"],
                        },
                        {
                            "path": "time_distributed",
                            "title": "TimeDistributed layer",
                            "generate": ["keras.layers.TimeDistributed"],
                        },
                        {
                            "path": "bidirectional",
                            "title": "Bidirectional layer",
                            "generate": ["keras.layers.Bidirectional"],
                        },
                        {
                            "path": "conv_lstm1d",
                            "title": "ConvLSTM1D layer",
                            "generate": ["keras.layers.ConvLSTM1D"],
                        },
                        {
                            "path": "conv_lstm2d",
                            "title": "ConvLSTM2D layer",
                            "generate": ["keras.layers.ConvLSTM2D"],
                        },
                        {
                            "path": "conv_lstm3d",
                            "title": "ConvLSTM3D layer",
                            "generate": ["keras.layers.ConvLSTM3D"],
                        },
                        {
                            "path": "rnn",
                            "title": "Base RNN layer",
                            "generate": ["keras.layers.RNN"],
                        },
                    ],
                },
                {
                    "path": "preprocessing_layers/",
                    "title": "Preprocessing layers",
                    "toc": True,
                    "children": [
                        {
                            "path": "text/",
                            "title": "Text preprocessing",
                            "toc": True,
                            "children": [
                                {
                                    "path": "text_vectorization",
                                    "title": "TextVectorization layer",
                                    "generate": ["keras.layers.TextVectorization"],
                                },
                            ],
                        },
                        {
                            "path": "numerical/",
                            "title": "Numerical features preprocessing layers",
                            "toc": True,
                            "children": [
                                {
                                    "path": "normalization",
                                    "title": "Normalization layer",
                                    "generate": ["keras.layers.Normalization"],
                                },
                                {
                                    "path": "discretization",
                                    "title": "Discretization layer",
                                    "generate": ["keras.layers.Discretization"],
                                },
                            ],
                        },
                        {
                            "path": "categorical/",
                            "title": "Categorical features preprocessing layers",
                            "toc": True,
                            "children": [
                                {
                                    "path": "category_encoding",
                                    "title": "CategoryEncoding layer",
                                    "generate": ["keras.layers.CategoryEncoding"],
                                },
                                {
                                    "path": "hashing",
                                    "title": "Hashing layer",
                                    "generate": ["keras.layers.Hashing"],
                                },
                                {
                                    "path": "hashed_crossing",
                                    "title": "HashedCrossing layer",
                                    "generate": ["keras.layers.HashedCrossing"],
                                },
                                {
                                    "path": "string_lookup",
                                    "title": "StringLookup layer",
                                    "generate": ["keras.layers.StringLookup"],
                                },
                                {
                                    "path": "integer_lookup",
                                    "title": "IntegerLookup layer",
                                    "generate": ["keras.layers.IntegerLookup"],
                                },
                            ],
                        },
                        {
                            "path": "image_preprocessing/",
                            "title": "Image preprocessing layers",
                            "toc": True,
                            "children": [
                                {
                                    "path": "resizing",
                                    "title": "Resizing layer",
                                    "generate": ["keras.layers.Resizing"],
                                },
                                {
                                    "path": "rescaling",
                                    "title": "Rescaling layer",
                                    "generate": ["keras.layers.Rescaling"],
                                },
                                {
                                    "path": "center_crop",
                                    "title": "CenterCrop layer",
                                    "generate": ["keras.layers.CenterCrop"],
                                },
                            ],
                        },
                        {
                            "path": "image_augmentation/",
                            "title": "Image augmentation layers",
                            "toc": True,
                            "children": [
                                {
                                    "path": "random_crop",
                                    "title": "RandomCrop layer",
                                    "generate": ["keras.layers.RandomCrop"],
                                },
                                {
                                    "path": "random_flip",
                                    "title": "RandomFlip layer",
                                    "generate": ["keras.layers.RandomFlip"],
                                },
                                {
                                    "path": "random_translation",
                                    "title": "RandomTranslation layer",
                                    "generate": ["keras.layers.RandomTranslation"],
                                },
                                {
                                    "path": "random_rotation",
                                    "title": "RandomRotation layer",
                                    "generate": ["keras.layers.RandomRotation"],
                                },
                                {
                                    "path": "random_zoom",
                                    "title": "RandomZoom layer",
                                    "generate": ["keras.layers.RandomZoom"],
                                },
                                {
                                    "path": "random_contrast",
                                    "title": "RandomContrast layer",
                                    "generate": ["keras.layers.RandomContrast"],
                                },
                                {
                                    "path": "random_brightness",
                                    "title": "RandomBrightness layer",
                                    "generate": ["keras.layers.RandomBrightness"],
                                },
                            ],
                        },
                    ],
                },
                {
                    "path": "normalization_layers/",
                    "title": "Normalization layers",
                    "toc": True,
                    "children": [
                        {
                            "path": "batch_normalization",
                            "title": "BatchNormalization layer",
                            "generate": ["keras.layers.BatchNormalization"],
                        },
                        {
                            "path": "layer_normalization",
                            "title": "LayerNormalization layer",
                            "generate": ["keras.layers.LayerNormalization"],
                        },
                        {
                            "path": "unit_normalization",
                            "title": "UnitNormalization layer",
                            "generate": ["keras.layers.UnitNormalization"],
                        },
                        {
                            "path": "group_normalization",
                            "title": "GroupNormalization layer",
                            "generate": ["keras.layers.GroupNormalization"],
                        },
                    ],
                },
                {
                    "path": "regularization_layers/",
                    "title": "Regularization layers",
                    "toc": True,
                    "children": [
                        {
                            "path": "dropout",
                            "title": "Dropout layer",
                            "generate": ["keras.layers.Dropout"],
                        },
                        {
                            "path": "spatial_dropout1d",
                            "title": "SpatialDropout1D layer",
                            "generate": ["keras.layers.SpatialDropout1D"],
                        },
                        {
                            "path": "spatial_dropout2d",
                            "title": "SpatialDropout2D layer",
                            "generate": ["keras.layers.SpatialDropout2D"],
                        },
                        {
                            "path": "spatial_dropout3d",
                            "title": "SpatialDropout3D layer",
                            "generate": ["keras.layers.SpatialDropout3D"],
                        },
                        {
                            "path": "gaussian_dropout",
                            "title": "GaussianDropout layer",
                            "generate": ["keras.layers.GaussianDropout"],
                        },
                        {
                            "path": "gaussian_noise",
                            "title": "GaussianNoise layer",
                            "generate": ["keras.layers.GaussianNoise"],
                        },
                        {
                            "path": "activity_regularization",
                            "title": "ActivityRegularization layer",
                            "generate": ["keras.layers.ActivityRegularization"],
                        },
                    ],
                },
                {
                    "path": "attention_layers/",
                    "title": "Attention layers",
                    "toc": True,
                    "children": [
                        {
                            "path": "multi_head_attention",
                            "title": "MultiHeadAttention layer",
                            "generate": ["keras.layers.MultiHeadAttention"],
                        },
                        {
                            "path": "attention",
                            "title": "Attention layer",
                            "generate": ["keras.layers.Attention"],
                        },
                        {
                            "path": "additive_attention",
                            "title": "AdditiveAttention layer",
                            "generate": ["keras.layers.AdditiveAttention"],
                        },
                    ],
                },
                {
                    "path": "reshaping_layers/",
                    "title": "Reshaping layers",
                    "toc": True,
                    "children": [
                        {
                            "path": "reshape",
                            "title": "Reshape layer",
                            "generate": ["keras.layers.Reshape"],
                        },
                        {
                            "path": "flatten",
                            "title": "Flatten layer",
                            "generate": ["keras.layers.Flatten"],
                        },
                        {
                            "path": "repeat_vector",
                            "title": "RepeatVector layer",
                            "generate": ["keras.layers.RepeatVector"],
                        },
                        {
                            "path": "permute",
                            "title": "Permute layer",
                            "generate": ["keras.layers.Permute"],
                        },
                        {
                            "path": "cropping1d",
                            "title": "Cropping1D layer",
                            "generate": ["keras.layers.Cropping1D"],
                        },
                        {
                            "path": "cropping2d",
                            "title": "Cropping2D layer",
                            "generate": ["keras.layers.Cropping2D"],
                        },
                        {
                            "path": "cropping3d",
                            "title": "Cropping3D layer",
                            "generate": ["keras.layers.Cropping3D"],
                        },
                        {
                            "path": "up_sampling1d",
                            "title": "UpSampling1D layer",
                            "generate": ["keras.layers.UpSampling1D"],
                        },
                        {
                            "path": "up_sampling2d",
                            "title": "UpSampling2D layer",
                            "generate": ["keras.layers.UpSampling2D"],
                        },
                        {
                            "path": "up_sampling3d",
                            "title": "UpSampling3D layer",
                            "generate": ["keras.layers.UpSampling3D"],
                        },
                        {
                            "path": "zero_padding1d",
                            "title": "ZeroPadding1D layer",
                            "generate": ["keras.layers.ZeroPadding1D"],
                        },
                        {
                            "path": "zero_padding2d",
                            "title": "ZeroPadding2D layer",
                            "generate": ["keras.layers.ZeroPadding2D"],
                        },
                        {
                            "path": "zero_padding3d",
                            "title": "ZeroPadding3D layer",
                            "generate": ["keras.layers.ZeroPadding3D"],
                        },
                    ],
                },
                {
                    "path": "merging_layers/",
                    "title": "Merging layers",
                    "toc": True,
                    "children": [
                        {
                            "path": "concatenate",
                            "title": "Concatenate layer",
                            "generate": ["keras.layers.Concatenate"],
                        },
                        {
                            "path": "average",
                            "title": "Average layer",
                            "generate": ["keras.layers.Average"],
                        },
                        {
                            "path": "maximum",
                            "title": "Maximum layer",
                            "generate": ["keras.layers.Maximum"],
                        },
                        {
                            "path": "minimum",
                            "title": "Minimum layer",
                            "generate": ["keras.layers.Minimum"],
                        },
                        {
                            "path": "add",
                            "title": "Add layer",
                            "generate": ["keras.layers.Add"],
                        },
                        {
                            "path": "subtract",
                            "title": "Subtract layer",
                            "generate": ["keras.layers.Subtract"],
                        },
                        {
                            "path": "multiply",
                            "title": "Multiply layer",
                            "generate": ["keras.layers.Multiply"],
                        },
                        {
                            "path": "dot",
                            "title": "Dot layer",
                            "generate": ["keras.layers.Dot"],
                        },
                    ],
                },
                {
                    "path": "activation_layers/",
                    "title": "Activation layers",
                    "toc": True,
                    "children": [
                        {
                            "path": "relu",
                            "title": "ReLU layer",
                            "generate": ["keras.layers.ReLU"],
                        },
                        {
                            "path": "softmax",
                            "title": "Softmax layer",
                            "generate": ["keras.layers.Softmax"],
                        },
                        {
                            "path": "leaky_relu",
                            "title": "LeakyReLU layer",
                            "generate": ["keras.layers.LeakyReLU"],
                        },
                        {
                            "path": "prelu",
                            "title": "PReLU layer",
                            "generate": ["keras.layers.PReLU"],
                        },
                        {
                            "path": "elu",
                            "title": "ELU layer",
                            "generate": ["keras.layers.ELU"],
                        },
                    ],
                },
            ],
        },
        {
            "path": "callbacks/",
            "title": "Callbacks API",
            "toc": True,
            "children": [
                {
                    "path": "base_callback",
                    "title": "Base Callback class",
                    "generate": ["keras.callbacks.Callback"],
                },
                {
                    "path": "model_checkpoint",
                    "title": "ModelCheckpoint",
                    "generate": ["keras.callbacks.ModelCheckpoint"],
                },
                # {
                #     "path": "backup_and_restore",
                #     "title": "BackupAndRestore",
                #     "generate": ["keras.callbacks.BackupAndRestore"],
                # },
                {
                    "path": "tensorboard",
                    "title": "TensorBoard",
                    "generate": ["keras.callbacks.TensorBoard"],
                },
                {
                    "path": "early_stopping",
                    "title": "EarlyStopping",
                    "generate": ["keras.callbacks.EarlyStopping"],
                },
                {
                    "path": "learning_rate_scheduler",
                    "title": "LearningRateScheduler",
                    "generate": ["keras.callbacks.LearningRateScheduler"],
                },
                {
                    "path": "reduce_lr_on_plateau",
                    "title": "ReduceLROnPlateau",
                    "generate": ["keras.callbacks.ReduceLROnPlateau"],
                },
                {
                    "path": "remote_monitor",
                    "title": "RemoteMonitor",
                    "generate": ["keras.callbacks.RemoteMonitor"],
                },
                {
                    "path": "lambda_callback",
                    "title": "LambdaCallback",
                    "generate": ["keras.callbacks.LambdaCallback"],
                },
                {
                    "path": "terminate_on_nan",
                    "title": "TerminateOnNaN",
                    "generate": ["keras.callbacks.TerminateOnNaN"],
                },
                {
                    "path": "csv_logger",
                    "title": "CSVLogger",
                    "generate": ["keras.callbacks.CSVLogger"],
                },
                {
                    "path": "progbar_logger",
                    "title": "ProgbarLogger",
                    "generate": ["keras.callbacks.ProgbarLogger"],
                },
            ],
        },
        {
            "path": "ops/",  # TODO: improve
            "title": "Ops API",
            "toc": True,
            "children": [
                {
                    "path": "numpy/",
                    "title": "NumPy ops",
                    "generate": [
                        "keras.ops.absolute",
                        "keras.ops.add",
                        "keras.ops.all",
                        "keras.ops.amax",
                        "keras.ops.amin",
                        "keras.ops.any",
                        "keras.ops.append",
                        "keras.ops.arange",
                        "keras.ops.arccos",
                        "keras.ops.arccosh",
                        "keras.ops.arcsin",
                        "keras.ops.arcsinh",
                        "keras.ops.arctan",
                        "keras.ops.arctan2",
                        "keras.ops.arctanh",
                        "keras.ops.argmax",
                        "keras.ops.argmin",
                        "keras.ops.argsort",
                        "keras.ops.array",
                        "keras.ops.average",
                        "keras.ops.bincount",
                        "keras.ops.broadcast_to",
                        "keras.ops.ceil",
                        "keras.ops.clip",
                        "keras.ops.concatenate",
                        "keras.ops.conj",
                        "keras.ops.conjugate",
                        "keras.ops.copy",
                        "keras.ops.cos",
                        "keras.ops.cosh",
                        "keras.ops.count_nonzero",
                        "keras.ops.cross",
                        "keras.ops.cumprod",
                        "keras.ops.cumsum",
                        "keras.ops.diag",
                        "keras.ops.diagonal",
                        "keras.ops.diff",
                        "keras.ops.digitize",
                        "keras.ops.divide",
                        "keras.ops.dot",
                        "keras.ops.einsum",
                        "keras.ops.empty",
                        "keras.ops.equal",
                        "keras.ops.exp",
                        "keras.ops.expand_dims",
                        "keras.ops.expm1",
                        "keras.ops.eye",
                        "keras.ops.flip",
                        "keras.ops.floor",
                        "keras.ops.floor_divide",
                        "keras.ops.full",
                        "keras.ops.full_like",
                        "keras.ops.get_item",
                        "keras.ops.greater",
                        "keras.ops.greater_equal",
                        "keras.ops.hstack",
                        "keras.ops.identity",
                        "keras.ops.imag",
                        "keras.ops.isclose",
                        "keras.ops.isfinite",
                        "keras.ops.isinf",
                        "keras.ops.isnan",
                        "keras.ops.less",
                        "keras.ops.less_equal",
                        "keras.ops.linspace",
                        "keras.ops.log",
                        "keras.ops.log10",
                        "keras.ops.log1p",
                        "keras.ops.log2",
                        "keras.ops.logaddexp",
                        "keras.ops.logical_and",
                        "keras.ops.logical_not",
                        "keras.ops.logical_or",
                        "keras.ops.logical_xor",
                        "keras.ops.logspace",
                        "keras.ops.matmul",
                        "keras.ops.max",
                        "keras.ops.maximum",
                        "keras.ops.mean",
                        "keras.ops.median",
                        "keras.ops.meshgrid",
                        "keras.ops.min",
                        "keras.ops.minimum",
                        "keras.ops.mod",
                        "keras.ops.moveaxis",
                        "keras.ops.multiply",
                        "keras.ops.nan_to_num",
                        "keras.ops.ndim",
                        "keras.ops.negative",
                        "keras.ops.nonzero",
                        "keras.ops.not_equal",
                        "keras.ops.ones",
                        "keras.ops.ones_like",
                        "keras.ops.outer",
                        "keras.ops.pad",
                        "keras.ops.power",
                        "keras.ops.prod",
                        "keras.ops.quantile",
                        "keras.ops.ravel",
                        "keras.ops.real",
                        "keras.ops.reciprocal",
                        "keras.ops.repeat",
                        "keras.ops.reshape",
                        "keras.ops.roll",
                        "keras.ops.round",
                        "keras.ops.sign",
                        "keras.ops.sin",
                        "keras.ops.sinh",
                        "keras.ops.size",
                        "keras.ops.sort",
                        "keras.ops.split",
                        "keras.ops.sqrt",
                        "keras.ops.square",
                        "keras.ops.squeeze",
                        "keras.ops.stack",
                        "keras.ops.std",
                        "keras.ops.subtract",
                        "keras.ops.sum",
                        "keras.ops.swapaxes",
                        "keras.ops.take",
                        "keras.ops.take_along_axis",
                        "keras.ops.tan",
                        "keras.ops.tanh",
                        "keras.ops.tensordot",
                        "keras.ops.tile",
                        "keras.ops.trace",
                        "keras.ops.transpose",
                        "keras.ops.tri",
                        "keras.ops.tril",
                        "keras.ops.triu",
                        "keras.ops.true_divide",
                        "keras.ops.var",
                        "keras.ops.vdot",
                        "keras.ops.vstack",
                        "keras.ops.where",
                        "keras.ops.zeros",
                        "keras.ops.zeros_like",
                    ],
                },
                {
                    "path": "nn/",
                    "title": "NN ops",
                    "generate": [
                        "keras.ops.average_pool",
                        "keras.ops.batch_normalization",
                        "keras.ops.binary_crossentropy",
                        "keras.ops.categorical_crossentropy",
                        "keras.ops.conv",
                        "keras.ops.conv_transpose",
                        "keras.ops.depthwise_conv",
                        "keras.ops.elu",
                        "keras.ops.gelu",
                        "keras.ops.hard_sigmoid",
                        "keras.ops.leaky_relu",
                        "keras.ops.log_sigmoid",
                        "keras.ops.log_softmax",
                        "keras.ops.max_pool",
                        "keras.ops.moments",
                        "keras.ops.multi_hot",
                        "keras.ops.one_hot",
                        "keras.ops.relu",
                        "keras.ops.relu6",
                        "keras.ops.selu",
                        "keras.ops.separable_conv",
                        "keras.ops.sigmoid",
                        "keras.ops.silu",
                        "keras.ops.softmax",
                        "keras.ops.softplus",
                        "keras.ops.softsign",
                        "keras.ops.sparse_categorical_crossentropy",
                        "keras.ops.swish",
                    ],
                },
                {
                    "path": "core/",
                    "title": "Core ops",
                    "generate": [
                        "keras.ops.cast",
                        "keras.ops.cond",
                        "keras.ops.convert_to_numpy",
                        "keras.ops.convert_to_tensor",
                        "keras.ops.erf",
                        "keras.ops.extract_sequences",
                        "keras.ops.fori_loop",
                        "keras.ops.in_top_k",
                        "keras.ops.is_tensor",
                        "keras.ops.logsumexp",
                        "keras.ops.qr",
                        "keras.ops.rsqrt",
                        "keras.ops.scatter",
                        "keras.ops.scatter_update",
                        "keras.ops.segment_max",
                        "keras.ops.segment_sum",
                        "keras.ops.shape",
                        "keras.ops.slice",
                        "keras.ops.slice_update",
                        "keras.ops.solve",
                        "keras.ops.stop_gradient",
                        "keras.ops.top_k",
                        "keras.ops.unstack",
                        "keras.ops.vectorized_map",
                        "keras.ops.while_loop",
                    ],
                },
                {
                    "path": "image/",
                    "title": "Image ops",
                    "generate": [
                        "keras.ops.image.affine_transform",
                        "keras.ops.image.extract_patches",
                        "keras.ops.image.map_coordinates",
                        "keras.ops.image.pad_images",
                        "keras.ops.image.resize",
                    ],
                },
                {
                    "path": "fft/",
                    "title": "FFT ops",
                    "generate": [
                        "keras.ops.fft",
                        "keras.ops.fft2",
                        "keras.ops.rfft",
                        "keras.ops.stft",
                        "keras.ops.irfft",
                        "keras.ops.istft",
                    ],
                },
            ],
        },
        {
            "path": "optimizers/",
            "title": "Optimizers",
            "toc": True,
            "generate": [
                "keras.optimizers.Optimizer.apply_gradients",
                "keras.optimizers.Optimizer.variables",
            ],
            "children": [
                {
                    "path": "sgd",
                    "title": "SGD",
                    "generate": ["keras.optimizers.SGD"],
                },
                {
                    "path": "rmsprop",
                    "title": "RMSprop",
                    "generate": ["keras.optimizers.RMSprop"],
                },
                {
                    "path": "adam",
                    "title": "Adam",
                    "generate": ["keras.optimizers.Adam"],
                },
                {
                    "path": "adamw",
                    "title": "AdamW",
                    "generate": ["keras.optimizers.AdamW"],
                },
                {
                    "path": "adadelta",
                    "title": "Adadelta",
                    "generate": ["keras.optimizers.Adadelta"],
                },
                {
                    "path": "adagrad",
                    "title": "Adagrad",
                    "generate": ["keras.optimizers.Adagrad"],
                },
                {
                    "path": "adamax",
                    "title": "Adamax",
                    "generate": ["keras.optimizers.Adamax"],
                },
                {
                    "path": "adafactor",
                    "title": "Adafactor",
                    "generate": ["keras.optimizers.Adafactor"],
                },
                {
                    "path": "Nadam",
                    "title": "Nadam",
                    "generate": ["keras.optimizers.Nadam"],
                },
                {
                    "path": "ftrl",
                    "title": "Ftrl",
                    "generate": ["keras.optimizers.Ftrl"],
                },
                {
                    "path": "learning_rate_schedules/",
                    "title": "Learning rate schedules API",
                    "toc": True,
                    "skip_from_toc": True,
                    "children": [
                        {
                            "path": "exponential_decay",
                            "title": "ExponentialDecay",
                            "generate": ["keras.optimizers.schedules.ExponentialDecay"],
                        },
                        {
                            "path": "piecewise_constant_decay",
                            "title": "PiecewiseConstantDecay",
                            "generate": [
                                "keras.optimizers.schedules.PiecewiseConstantDecay"
                            ],
                        },
                        {
                            "path": "polynomial_decay",
                            "title": "PolynomialDecay",
                            "generate": ["keras.optimizers.schedules.PolynomialDecay"],
                        },
                        {
                            "path": "inverse_time_decay",
                            "title": "InverseTimeDecay",
                            "generate": ["keras.optimizers.schedules.InverseTimeDecay"],
                        },
                        {
                            "path": "cosine_decay",
                            "title": "CosineDecay",
                            "generate": ["keras.optimizers.schedules.CosineDecay"],
                        },
                        {
                            "path": "cosine_decay_restarts",
                            "title": "CosineDecayRestarts",
                            "generate": [
                                "keras.optimizers.schedules.CosineDecayRestarts"
                            ],
                        },
                    ],
                },
            ],
        },
        {
            "path": "metrics/",
            "title": "Metrics",
            "toc": True,
            "children": [
                {
                    "path": "accuracy_metrics",
                    "title": "Accuracy metrics",
                    "generate": [
                        "keras.metrics.Accuracy",
                        "keras.metrics.BinaryAccuracy",
                        "keras.metrics.CategoricalAccuracy",
                        "keras.metrics.SparseCategoricalAccuracy",
                        "keras.metrics.TopKCategoricalAccuracy",
                        "keras.metrics.SparseTopKCategoricalAccuracy",
                    ],
                },
                {
                    "path": "probabilistic_metrics",
                    "title": "Probabilistic metrics",
                    "generate": [
                        "keras.metrics.BinaryCrossentropy",
                        "keras.metrics.CategoricalCrossentropy",
                        "keras.metrics.SparseCategoricalCrossentropy",
                        "keras.metrics.KLDivergence",
                        "keras.metrics.Poisson",
                    ],
                },
                {
                    "path": "regression_metrics",
                    "title": "Regression metrics",
                    "generate": [
                        "keras.metrics.MeanSquaredError",
                        "keras.metrics.RootMeanSquaredError",
                        "keras.metrics.MeanAbsoluteError",
                        "keras.metrics.MeanAbsolutePercentageError",
                        "keras.metrics.MeanSquaredLogarithmicError",
                        "keras.metrics.CosineSimilarity",
                        "keras.metrics.LogCoshError",
                    ],
                },
                {
                    "path": "classification_metrics",
                    "title": "Classification metrics based on True/False positives & negatives",
                    "generate": [
                        "keras.metrics.AUC",
                        "keras.metrics.Precision",
                        "keras.metrics.Recall",
                        "keras.metrics.TruePositives",
                        "keras.metrics.TrueNegatives",
                        "keras.metrics.FalsePositives",
                        "keras.metrics.FalseNegatives",
                        "keras.metrics.PrecisionAtRecall",
                        "keras.metrics.SensitivityAtSpecificity",
                        "keras.metrics.SpecificityAtSensitivity",
                    ],
                },
                {
                    "path": "segmentation_metrics",
                    "title": "Image segmentation metrics",
                    "generate": ["keras.metrics.MeanIoU"],
                },
                {
                    "path": "hinge_metrics",
                    "title": 'Hinge metrics for "maximum-margin" classification',
                    "generate": [
                        "keras.metrics.Hinge",
                        "keras.metrics.SquaredHinge",
                        "keras.metrics.CategoricalHinge",
                    ],
                },
            ],
        },
        {
            "path": "losses/",
            "title": "Losses",
            "toc": True,
            "children": [
                {
                    "path": "probabilistic_losses",
                    "title": "Probabilistic losses",
                    "generate": [
                        "keras.losses.BinaryCrossentropy",
                        "keras.losses.CategoricalCrossentropy",
                        "keras.losses.SparseCategoricalCrossentropy",
                        "keras.losses.Poisson",
                        "keras.losses.binary_crossentropy",
                        "keras.losses.categorical_crossentropy",
                        "keras.losses.sparse_categorical_crossentropy",
                        "keras.losses.poisson",
                        "keras.losses.KLDivergence",
                        "keras.losses.kl_divergence",
                    ],
                },
                {
                    "path": "regression_losses",
                    "title": "Regression losses",
                    "generate": [
                        "keras.losses.MeanSquaredError",
                        "keras.losses.MeanAbsoluteError",
                        "keras.losses.MeanAbsolutePercentageError",
                        "keras.losses.MeanSquaredLogarithmicError",
                        "keras.losses.CosineSimilarity",
                        "keras.losses.mean_squared_error",
                        "keras.losses.mean_absolute_error",
                        "keras.losses.mean_absolute_percentage_error",
                        "keras.losses.mean_squared_logarithmic_error",
                        "keras.losses.cosine_similarity",
                        "keras.losses.Huber",
                        "keras.losses.huber",
                        "keras.losses.LogCosh",
                        "keras.losses.log_cosh",
                    ],
                },
                {
                    "path": "hinge_losses",
                    "title": 'Hinge losses for "maximum-margin" classification',
                    "generate": [
                        "keras.losses.Hinge",
                        "keras.losses.SquaredHinge",
                        "keras.losses.CategoricalHinge",
                        "keras.losses.hinge",
                        "keras.losses.squared_hinge",
                        "keras.losses.categorical_hinge",
                    ],
                },
            ],
        },
        {
            "path": "data_loading/",
            "title": "Data loading",
            "toc": True,
            "children": [
                {
                    "path": "image",
                    "title": "Image data loading",
                    "generate": [
                        "keras.utils.image_dataset_from_directory",
                        "keras.utils.load_img",
                        "keras.utils.img_to_array",
                        "keras.utils.save_img",
                    ],
                },
                {
                    "path": "timeseries",
                    "title": "Timeseries data loading",
                    "generate": [
                        "keras.utils.timeseries_dataset_from_array",
                        "keras.utils.pad_sequences",  # LEGACY
                    ],
                },
                {
                    "path": "text",
                    "title": "Text data loading",
                    "generate": [
                        "keras.utils.text_dataset_from_directory",
                    ],
                },
                {
                    "path": "audio",
                    "title": "Audio data loading",
                    "generate": [
                        "keras.utils.audio_dataset_from_directory",
                    ],
                },
            ],
        },
        {
            "path": "datasets/",
            "title": "Built-in small datasets",
            "toc": True,
            "children": [
                {
                    "path": "mnist",
                    "title": "MNIST digits classification dataset",
                    "generate": ["keras.datasets.mnist.load_data"],
                },
                {
                    "path": "cifar10",
                    "title": "CIFAR10 small images classification dataset",
                    "generate": ["keras.datasets.cifar10.load_data"],
                },
                {
                    "path": "cifar100",
                    "title": "CIFAR100 small images classification dataset",
                    "generate": ["keras.datasets.cifar100.load_data"],
                },
                {
                    "path": "imdb",
                    "title": "IMDB movie review sentiment classification dataset",
                    "generate": [
                        "keras.datasets.imdb.load_data",
                        "keras.datasets.imdb.get_word_index",
                    ],
                },
                {
                    "path": "reuters",
                    "title": "Reuters newswire classification dataset",
                    "generate": [
                        "keras.datasets.reuters.load_data",
                        "keras.datasets.reuters.get_word_index",
                    ],
                },
                {
                    "path": "fashion_mnist",
                    "title": "Fashion MNIST dataset, an alternative to MNIST",
                    "generate": ["keras.datasets.fashion_mnist.load_data"],
                },
                {
                    "path": "california_housing",
                    "title": "California Housing price regression dataset",
                    "generate": ["keras.datasets.california_housing.load_data"],
                },
            ],
        },
        {
            "path": "applications/",
            "title": "Keras Applications",
            "children": [
                {
                    "path": "xception",
                    "title": "Xception",
                    "generate": ["keras.applications.Xception"],
                },
                {
                    "path": "efficientnet",
                    "title": "EfficientNet B0 to B7",
                    "generate": [
                        "keras.applications.EfficientNetB0",
                        "keras.applications.EfficientNetB1",
                        "keras.applications.EfficientNetB2",
                        "keras.applications.EfficientNetB3",
                        "keras.applications.EfficientNetB4",
                        "keras.applications.EfficientNetB5",
                        "keras.applications.EfficientNetB6",
                        "keras.applications.EfficientNetB7",
                    ],
                },
                {
                    "path": "efficientnet_v2",
                    "title": "EfficientNetV2 B0 to B3 and S, M, L",
                    "generate": [
                        "keras.applications.EfficientNetV2B0",
                        "keras.applications.EfficientNetV2B1",
                        "keras.applications.EfficientNetV2B2",
                        "keras.applications.EfficientNetV2B3",
                        "keras.applications.EfficientNetV2S",
                        "keras.applications.EfficientNetV2M",
                        "keras.applications.EfficientNetV2L",
                    ],
                },
                {
                    "path": "convnext",
                    "title": "ConvNeXt Tiny, Small, Base, Large, XLarge",
                    "generate": [
                        "keras.applications.ConvNeXtTiny",
                        "keras.applications.ConvNeXtSmall",
                        "keras.applications.ConvNeXtBase",
                        "keras.applications.ConvNeXtLarge",
                        "keras.applications.ConvNeXtXLarge",
                    ],
                },
                {
                    "path": "vgg",
                    "title": "VGG16 and VGG19",
                    "generate": [
                        "keras.applications.VGG16",
                        "keras.applications.VGG19",
                    ],
                },
                {
                    "path": "resnet",
                    "title": "ResNet and ResNetV2",
                    "generate": [
                        "keras.applications.ResNet50",
                        "keras.applications.ResNet101",
                        "keras.applications.ResNet152",
                        "keras.applications.ResNet50V2",
                        "keras.applications.ResNet101V2",
                        "keras.applications.ResNet152V2",
                    ],
                },
                {
                    "path": "mobilenet",
                    "title": "MobileNet, MobileNetV2, and MobileNetV3",
                    "generate": [
                        "keras.applications.MobileNet",
                        "keras.applications.MobileNetV2",
                        "keras.applications.MobileNetV3Small",
                        "keras.applications.MobileNetV3Large",
                    ],
                },
                {
                    "path": "densenet",
                    "title": "DenseNet",
                    "generate": [
                        "keras.applications.DenseNet121",
                        "keras.applications.DenseNet169",
                        "keras.applications.DenseNet201",
                    ],
                },
                {
                    "path": "nasnet",
                    "title": "NasNetLarge and NasNetMobile",
                    "generate": [
                        "keras.applications.NASNetLarge",
                        "keras.applications.NASNetMobile",
                    ],
                },
                {
                    "path": "inceptionv3",
                    "title": "InceptionV3",
                    "generate": [
                        "keras.applications.InceptionV3",
                    ],
                },
                {
                    "path": "inceptionresnetv2",
                    "title": "InceptionResNetV2",
                    "generate": [
                        "keras.applications.InceptionResNetV2",
                    ],
                },
            ],
        },
        {
            "path": "mixed_precision/",
            "title": "Mixed precision",
            "toc": True,
            "children": [
                {
                    "path": "policy",
                    "title": "Mixed precision policy API",
                    "generate": [
                        "keras.mixed_precision.DTypePolicy",
                        "keras.mixed_precision.dtype_policy",
                        "keras.mixed_precision.set_dtype_policy",
                    ],
                },
            ],
        },
        {
            "path": "distribution/",
            "title": "Multi-device distribution",
            "toc": True,
            "children": [
                {
                    "path": "layout_map",
                    "title": "LayoutMap API",
                    "generate": [
                        "keras.distribution.LayoutMap",
                        "keras.distribution.DeviceMesh",
                        "keras.distribution.TensorLayout",
                        "keras.distribution.distribute_tensor",
                    ],
                },
                {
                    "path": "data_parallel",
                    "title": "DataParallel API",
                    "generate": [
                        "keras.distribution.DataParallel",
                    ],
                },
                {
                    "path": "model_parallel",
                    "title": "ModelParallel API",
                    "generate": [
                        "keras.distribution.ModelParallel",
                    ],
                },
                {
                    "path": "model_parallel",
                    "title": "ModelParallel API",
                    "generate": [
                        "keras.distribution.ModelParallel",
                    ],
                },
                {
                    "path": "distribution_utils",
                    "title": "Distribution utilities",
                    "generate": [
                        "keras.distribution.set_distribution",
                        "keras.distribution.distribution",
                        "keras.distribution.list_devices",
                        "keras.distribution.initialize",
                    ],
                },
            ],
        },
        {
            "path": "random/",
            "title": "RNG API",
            "toc": True,
            "children": [
                {
                    "path": "seed_generator",
                    "title": "SeedGenerator class",
                    "generate": ["keras.random.SeedGenerator"],
                },
                {
                    "path": "random_ops",
                    "title": "Random operations",
                    "generate": [
                        "keras.random.categorical",
                        "keras.random.dropout",
                        "keras.random.gamma",
                        "keras.random.normal",
                        "keras.random.randint",
                        "keras.random.shuffle",
                        "keras.random.truncated_normal",
                        "keras.random.uniform",
                    ],
                },
            ],
        },
        {
            "path": "utils/",
            "title": "Utilities",
            "toc": True,
            "children": [
                {
                    "path": "model_plotting_utils",
                    "title": "Model plotting utilities",
                    "generate": [
                        "keras.utils.plot_model",
                        "keras.utils.model_to_dot",
                    ],
                },
                {
                    "path": "feature_space",
                    "title": "Structured data preprocessing utilities",
                    "generate": [
                        "keras.utils.FeatureSpace",
                    ],
                },
                {
                    "path": "python_utils",
                    "title": "Python & NumPy utilities",
                    "generate": [
                        "keras.utils.set_random_seed",
                        "keras.utils.split_dataset",
                        "keras.utils.get_file",
                        "keras.utils.Progbar",
                        "keras.utils.PyDataset",
                        "keras.utils.to_categorical",
                        "keras.utils.normalize",
                    ],
                },
                {
                    "path": "config_utils",
                    "title": "Keras configuration utilities",
                    "generate": [
                        "keras.utils.clear_session",
                        "keras.config.floatx",
                        "keras.config.set_floatx",
                        "keras.config.image_data_format",
                        "keras.config.set_image_data_format",
                        "keras.config.epsilon",
                        "keras.config.set_epsilon",
                    ],
                },
            ],
        },
        KT_API_MASTER,
        CV_API_MASTER,
        NLP_API_MASTER,
    ],
}
