
EXAMPLES_MASTER = {
    'path': 'examples/',
    'title': 'Code examples',
    'toc': True,
    'children': [
        {
            'path': 'vision/',
            'title': 'Computer Vision',
            'toc': True,
            'children': [
                # Will be autogenerated
            ]
        },
        {
            'path': 'nlp/',
            'title': 'Natural language processing',
            'toc': True,
            'children': [
                # Will be autogenerated
            ]
        },
        {
            'path': 'structured_data/',
            'title': 'Structured Data',
            'toc': True,
            'children': [
                # Will be autogenerated
            ]
        },
        # {
        #     'path': 'timeseries/',
        #     'title': 'Timeseries',
        #     'toc': True,
        #     'children': [
        #         # Will be autogenerated
        #     ]
        # },
        {
            'path': 'generative/',
            'title': 'Generative Deep Learning',
            'toc': True,
            'children': [
                # Will be autogenerated
            ]
        },
        {
            'path': 'keras_recipes/',
            'title': 'Quick Keras recipes',
            'toc': True,
            'children': [
                # Will be autogenerated
            ]
        },
    ]
}
