EXAMPLES_MASTER = {
    "path": "examples/",
    "title": "Code examples",
    "toc": True,
    "children": [
        {
            "path": "vision/",
            "title": "Computer Vision",
            "toc": True,
            "children": [
                {
                    "path": "image_classification_from_scratch",
                    "title": "Image classification from scratch",
                },
                {"path": "mnist_convnet", "title": "Simple MNIST convnet"},
                {
                    "path": "oxford_pets_image_segmentation",
                    "title": "Image segmentation with a U-Net-like architecture",
                },
                # Remainder will be autogenerated
            ],
        },
        {
            "path": "nlp/",
            "title": "Natural Language Processing",
            "toc": True,
            "children": [
                {
                    "path": "text_classification_from_scratch",
                    "title": "Text classification from scratch",
                },
                # Remainder will be autogenerated
            ],
        },
        {
            "path": "structured_data/",
            "title": "Structured Data",
            "toc": True,
            "children": [
                {
                    "path": "structured_data_classification_from_scratch",
                    "title": "Structured data classification from scratch",
                },
                # Remainder will be autogenerated
            ],
        },
        {
            "path": "timeseries/",
            "title": "Timeseries",
            "toc": True,
            "children": [
                # Will be autogenerated
            ],
        },
        {
            "path": "audio/",
            "title": "Audio Data",
            "toc": True,
            "children": [
                # Will be autogenerated
            ],
        },
        {
            "path": "generative/",
            "title": "Generative Deep Learning",
            "toc": True,
            "children": [
                {"path": "vae", "title": "Variational AutoEncoder"},
                {
                    "path": "dcgan_overriding_train_step",
                    "title": "GAN overriding `Model.train_step`",
                },
                {"path": "wgan_gp", "title": "WGAN-GP overriding `Model.train_step`"},
                {"path": "neural_style_transfer", "title": "Neural style transfer"},
                {"path": "deep_dream", "title": "Deep Dream"},
                # Remainder will be autogenerated
            ],
        },
        {
            "path": "rl/",
            "title": "Reinforcement Learning",
            "toc": True,
            "children": [
                # Will be autogenerated
            ],
        },
        {
            "path": "graph/",
            "title": "Graph Data",
            "toc": True,
            "children": [
                # Will be autogenerated
            ],
        },
        {
            "path": "keras_recipes/",
            "title": "Quick Keras Recipes",
            "toc": True,
            "children": [
                # Will be autogenerated
            ],
        },
    ],
}
