name: auto-assignment
on:
  issues:
    types:
      - opened
  pull_request_target:
    types: [opened]   

permissions:
  contents: read

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./\.github/workflows/scripts/auto-assignment.js')
            script({github, context})