name: Continuous integration

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.0
      with:
        persist-credentials: false
    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.0.0
      with:
        python-version: '3.11'
    - name: Ensure files are formatted with black
      run: |
        pip install --upgrade pip
        pip install black --upgrade
        black --check --diff ./examples
  docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.0
      with:
        persist-credentials: false
    - name: Ensure the docker image works and can start.
      run: |
        make container-test
